import type { Tool, Edge, ToolCategory, GraphData } from './types';

// Define categories with their levels and colors (Vercel-inspired palette)
export const categories: ToolCategory[] = [
  { id: 'metaframework', name: 'Meta Framework', level: 1, color: '#0070f3' },
  { id: 'framework', name: 'Framework', level: 2, color: '#00bcd4' },
  { id: 'library', name: 'Library', level: 3, color: '#f81ce5' },
  { id: 'bundler', name: 'Bundler', level: 4, color: '#ff6600' },
  { id: 'linter', name: 'Linter', level: 5, color: '#ffd93d' },
  { id: 'formatter', name: 'Formatter', level: 5, color: '#6bcf7f' },
  { id: 'minimizer', name: 'Minimizer', level: 5, color: '#ff4757' },
  { id: 'compiler', name: 'Compiler', level: 6, color: '#06ffa5' },
  { id: 'parser', name: 'Parser', level: 6, color: '#1fb6ff' },
  { id: 'runtime', name: 'Runtime', level: 7, color: '#4d4d4d' },
  { id: 'testing', name: 'Testing', level: 3, color: '#5f27cd' },
  { id: 'language-tool', name: 'Language Tool', level: 3, color: '#00d2d3' },
];

export const tools: Tool[] = [
  { name: 'TanStack Start', category: 'metaframework', logo: '/logos/tanstack-start.png', description: 'A modern, full-stack React framework for building web apps, by TanStack.' },
  { name: 'SolidStart', category: 'metaframework', logo: '/logos/solid-start.svg', description: 'The official application framework for SolidJS, supporting SSR and routing.' },
  { name: 'SvelteKit', category: 'metaframework', logo: '/logos/sveltekit.svg', description: 'The official framework for building web apps with Svelte, supporting SSR and more.' },
  { name: 'Qwik City', category: 'metaframework', logo: '/logos/qwik-city.png', description: 'Qwik is meta-framework for building instant-loading web apps.' },
  { name: 'Next.js', category: 'metaframework', logo: '/logos/nextjs.svg', description: 'The React framework for production, with hybrid static & server rendering.' },
  { name: 'Nuxt', category: 'metaframework', logo: '/logos/nuxt.svg', description: 'The intuitive Vue framework for building web applications.' },
  { name: 'Remix', category: 'metaframework', logo: '/logos/remix.svg', description: 'A full stack web framework focused on fast, dynamic user experiences.' },
  { name: 'Analog', category: 'metaframework', logo: '/logos/analog.svg', description: 'A meta-framework for Angular, inspired by Vite and Next.js.' },
  { name: 'Astro / Starlight', category: 'framework', logo: '/logos/astro.svg', description: 'A web framework for building fast, content-focused websites with any UI framework.' },
  { name: 'Mitosis', category: 'framework', logo: '/logos/mitosis.png', description: 'Write components once, run everywhere: compile to React, Vue, Svelte, and more.' },
  { name: 'Gatsby', category: 'framework', logo: '/logos/gatsby.svg', description: 'A React-based open source framework for creating websites and apps.' },
  { name: 'Docusaurus', category: 'framework', logo: '/logos/docusaurus.svg', description: 'A modern static website generator, optimized for documentation sites.' },
  { name: 'Nitro', category: 'framework', logo: '/logos/nitro.png', description: 'A server engine powering Nuxt and other frameworks, for serverless and edge.' },
  { name: 'UnJS libs', category: 'framework', logo: '/logos/unjs.png', description: 'A collection of high-quality JavaScript utilities and libraries by UnJS.' },
  { name: 'Unplugin', category: 'framework', logo: '/logos/unplugin.svg', description: 'Unified plugin system for Vite, Rollup, Webpack, and more.' },
  { name: 'React Router', category: 'framework', logo: '/logos/react-router.svg', description: 'Declarative routing for React applications.' },
  { name: 'Preact', category: 'library', logo: '/logos/preact.svg', description: 'A fast 3kB alternative to React with the same modern API.' },
  { name: 'React', category: 'library', logo: '/logos/react.svg', description: 'A JavaScript library for building user interfaces.' },
  { name: 'Angular', category: 'library', logo: '/logos/angular.svg', description: 'A platform for building mobile and desktop web applications.' },
  { name: 'Vue.js', category: 'library', logo: '/logos/vue.svg', description: 'The Progressive JavaScript Framework for building UIs.' },
  { name: 'Svelte', category: 'library', logo: '/logos/svelte.svg', description: 'Cybernetically enhanced web apps: a radical new approach to building UIs.' },
  { name: 'Qwik', category: 'library', logo: '/logos/qwik.png', description: 'A new kind of web framework for instant-loading sites.' },
  { name: 'Solid.js', category: 'library', logo: '/logos/solid.png', description: 'A declarative, efficient, and flexible JavaScript library for building UIs.' },
  { name: 'LIT', category: 'library', logo: '/logos/lit.svg', description: 'Simple, fast, web components with Lit.' },
  { name: 'Alpine', category: 'library', logo: '/logos/alpine.svg', description: 'A rugged, minimal framework for composing JavaScript behavior in your HTML.' },
  { name: 'Fresh', category: 'framework', logo: '/logos/fresh.png', description: 'A next-gen web framework for Deno, with zero runtime overhead.' },
  { name: 'Volar.js', category: 'language-tool', logo: '/logos/volar.svg', description: 'Language support for Vue 3 in VSCode and other editors.' },
  { name: 'Vitest', category: 'testing', logo: '/logos/vitest.svg', description: 'A blazing fast unit test framework powered by Vite.' },
  { name: 'Vite', category: 'bundler', logo: '/logos/vite.svg', description: 'Next Generation Frontend Tooling: fast, opinionated, and modern.' },
  { name: 'Parcel', category: 'bundler', logo: '/logos/parcel.svg', description: 'A zero configuration web application bundler.' },
  { name: 'Turbopack', category: 'bundler', logo: '/logos/turbopack.png', description: 'An incremental bundler and build system by Vercel.' },
  { name: 'Webpack', category: 'bundler', logo: '/logos/webpack.svg', description: 'A static module bundler for modern JavaScript applications.' },
  { name: 'Rspack', category: 'bundler', logo: '/logos/rspack.png', description: 'A fast Rust-based Webpack alternative.' },
  { name: 'Farm', category: 'bundler', logo: '/logos/farm.png', description: 'A blazing fast, extensible web build tool written in Rust.' },
  { name: 'esbuild', category: 'bundler', logo: '/logos/esbuild.svg', description: 'An extremely fast JavaScript bundler and minifier.' },
  { name: 'Rollup', category: 'bundler', logo: '/logos/rollup.svg', description: 'A module bundler for JavaScript, used for libraries and applications.' },
  { name: 'Rolldown', category: 'bundler', logo: '/logos/rolldown.svg', description: 'A Rust-based JavaScript bundler inspired by Rollup.' },
  { name: 'Biome', category: 'linter', logo: '/logos/biome.png', description: 'A fast, modern JavaScript linter, formatter, and more.' },
  { name: 'ESLint', category: 'linter', logo: '/logos/eslint.svg', description: 'The pluggable linting utility for JavaScript and JSX.' },
  { name: 'Oxlint', category: 'linter', logo: '/logos/oxlint.png', description: 'A fast JavaScript linter written in Rust.' },
  { name: 'Prettier', category: 'formatter', logo: '/logos/prettier.svg', description: 'An opinionated code formatter for consistent style.' },
  { name: 'Terser', category: 'minimizer', logo: '/logos/terser.svg', description: 'A JavaScript parser, mangler, and compressor toolkit for ES6+.' },
  { name: 'SWC', category: 'compiler', logo: '/logos/swc.svg', description: 'A super-fast JavaScript/TypeScript compiler written in Rust.' },
  { name: 'Babel', category: 'compiler', logo: '/logos/babel.svg', description: 'A JavaScript compiler for writing next generation JavaScript.' },
  { name: 'tsc', category: 'compiler', logo: '/logos/tsc.svg', description: 'The TypeScript compiler.' },
  { name: 'React Compiler', category: 'compiler', logo: '/logos/react-compiler.svg', description: 'A new compiler for optimizing React applications.' },
  { name: 'ts-node', category: 'compiler', logo: '/logos/tsnode.svg', description: 'TypeScript execution and REPL for node.js, with source maps.' },
  { name: 'Acorn', category: 'parser', logo: '/logos/acorn.svg', description: 'A tiny, fast JavaScript parser written in JavaScript.' },
  { name: 'OXC', category: 'compiler', logo: '/logos/oxc.png', description: 'A Rust-based JavaScript/TypeScript parser and toolkit.' },
  { name: 'Deno', category: 'runtime', logo: '/logos/deno.svg', description: 'A modern runtime for JavaScript and TypeScript, secure by default.' },
  { name: 'Bun', category: 'runtime', logo: '/logos/bun.svg', description: 'A fast all-in-one JavaScript runtime, bundler, and package manager.' },
].map(tool => {
  const cat = categories.find(c => c.id === tool.category)!;
  return {
    ...tool,
    id: tool.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    category: cat,
    level: cat.level
  };
});

// Raw edge data from the user
const rawEdges = [
  { source: 'SolidStart', target: 'Solid.js', label: 'Based on' },
  { source: 'Analog', target: 'Angular', label: 'Based on' },
  { source: 'Nuxt', target: 'Vue.js', label: 'Based on' },
  { source: 'Remix', target: 'React Router', label: 'V2 Turned into' },
  { source: 'React Router', target: 'React', label: 'based on' },
  { source: 'Remix', target: 'React', label: 'until v3 based on' },
  { source: 'React', target: 'Preact', label: 'V3 started based on' },
  { source: 'Next.js', target: 'React', label: 'Based on' },
  { source: 'Docusaurus', target: 'React', label: 'Based on' },
  { source: 'Gatsby', target: 'React', label: 'Based on' },
  { source: 'Fresh', target: 'Preact', label: 'Based on' },
  { source: 'Mitosis', target: 'Solid.js', label: 'Compiles to' },
  { source: 'Mitosis', target: 'Qwik', label: 'Compiles to' },
  { source: 'Mitosis', target: 'Angular', label: 'Compiles to' },
  { source: 'Mitosis', target: 'Vue.js', label: 'Compiles to' },
  { source: 'Mitosis', target: 'Svelte', label: 'Compiles to' },
  { source: 'Mitosis', target: 'React', label: 'Compiles to' },
  { source: 'Volar.js', target: 'Vue.js', label: 'Language tools' },
  { source: 'Volar.js', target: 'Astro / Starlight', label: 'Language tools' },
  { source: 'Astro / Starlight', target: 'Solid.js', label: 'Astro supports components of' },
  { source: 'Astro / Starlight', target: 'Qwik', label: 'With @qwikdev/astro' },
  { source: 'Astro / Starlight', target: 'Angular', label: 'With @analogjs/astro-angular' },
  { source: 'Astro / Starlight', target: 'Vue.js', label: 'Astro supports components of' },
  { source: 'Astro / Starlight', target: 'Svelte', label: 'Astro supports components of' },
  { source: 'Astro / Starlight', target: 'Preact', label: 'Astro supports components of' },
  { source: 'Astro / Starlight', target: 'React', label: 'Astro supports components of' },
  { source: 'TanStack Start', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'SolidStart', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'LIT', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'Qwik City', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'Analog', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'Nuxt', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'SvelteKit', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'Remix', target: 'Vite', label: 'Official bundling with' },
  { source: 'Remix', target: 'Webpack', label: 'Legacy bundling with' },
  { source: 'Next.js', target: 'Turbopack', label: 'dev from v13.1, build from v15.3 (experimental)' },
  { source: 'Vitest', target: 'Vite', label: 'build' },
  { source: 'Nuxt', target: 'Nitro', label: 'Use' },
  { source: 'Nitro', target: 'UnJS libs', label: 'Use' },
  { source: 'Vite', target: 'esbuild', label: 'Dev build' },
  { source: 'Vite', target: 'Rollup', label: 'Prod build' },
  { source: 'Vite', target: 'Rolldown', label: 'Build (experimental in v5)' },
  { source: 'Vite', target: 'rolldown-vite package', label: 'Use' },
  { source: 'rolldown-vite package', target: 'Rolldown', label: 'Dev & Prod Build' },
  { source: 'Webpack', target: 'Rspack', label: '1:1 replacement' },
  { source: 'Webpack', target: 'SWC', label: 'New loaders' },
  { source: 'Webpack', target: 'Terser', label: 'Common Minifier' },
  { source: 'esbuild', target: 'Rollup', label: 'successor' },
  { source: 'Rollup', target: 'Rolldown', label: 'successor' },
  { source: 'Rollup', target: 'Acorn', label: 'V3 and earlier parser' },
  { source: 'Rollup', target: 'OXC', label: 'V4 parser' },
  { source: 'Rollup', target: 'Terser', label: 'Common Minifier' },
  { source: 'Rolldown', target: 'OXC', label: 'Parser, Resolver, etc' },
  { source: 'Oxlint', target: 'OXC', label: 'Resolver' },
  { source: 'Oxlint', target: 'OXC', label: 'Experimental plugin' },
  { source: 'Biome', target: 'OXC', label: 'New JS/TS Plugin in v3.6' },
  { source: 'Biome', target: 'Prettier', label: 'Parser' },
  { source: 'Biome', target: 'ESLint', label: 'Parser' },
  { source: 'ESLint', target: 'Acorn', label: 'New parser (espree)' },
  { source: 'ESLint', target: 'Babel', label: 'Legacy parser (@babel/eslint-parser)' },
  { source: 'ESLint', target: 'tsc', label: 'TypeScript parser (@typescript-eslint/parser)' },
  { source: 'ESLint', target: 'SWC', label: 'Plugin (wip)' },
  { source: 'Prettier', target: 'Babel', label: 'Plugin' },
  { source: 'Prettier', target: 'Acorn', label: 'Parser' },
  { source: 'React Compiler', target: 'Babel', label: 'Plugin' },
  { source: 'React Compiler', target: 'SWC', label: 'Compiler' },
  { source: 'Unplugin', target: 'esbuild', label: 'Parse config files with' },
  { source: 'Unplugin', target: 'Acorn', label: 'Parse config files with' },
  { source: 'Terser', target: 'Acorn', label: 'parser (acorn/terser)' },
  { source: 'Vite', target: 'Unplugin', label: 'Use' },
  { source: 'Webpack', target: 'Unplugin', label: 'Use' },
  { source: 'Rollup', target: 'Unplugin', label: 'Use' },
  { source: 'esbuild', target: 'Unplugin', label: 'Use' },
  { source: 'Rspack', target: 'Unplugin', label: 'Use' },
  { source: 'Astro / Starlight', target: 'Acorn', label: 'Also used directly' },
  { source: 'SvelteKit', target: 'Acorn', label: 'Also used directly' },
  { source: 'Nuxt', target: 'Acorn', label: 'Also used directly' },
  { source: 'UnJS libs', target: 'Acorn', label: 'Also used directly' },
  { source: 'Fresh', target: 'Deno', label: 'Type checker' },
  { source: 'Deno', target: 'SWC', label: 'Type checker' },
  { source: 'ts-node', target: 'tsc', label: '' },
  { source: 'ts-node', target: 'SWC', label: '' },
  { source: 'ts-node', target: 'Bun', label: '' },
  { source: 'Turbopack', target: 'SWC', label: '' },
  { source: 'Rspack', target: 'SWC', label: '' },
  { source: 'Farm', target: 'SWC', label: '' },
  { source: 'Bun', target: 'SWC', label: '' },
  { source: 'esbuild', target: 'SWC', label: '' },
  { source: 'Parcel', target: 'SWC', label: '' },
  // SvelteKit uses Svelte
  { source: 'SvelteKit', target: 'Svelte', label: 'Uses' },
  // Qwik City uses Qwik
  { source: 'Qwik City', target: 'Qwik', label: 'Uses' },
];

// Transform raw data to typed structures
export const edges: Edge[] = rawEdges.filter(e => e.source !== 'rolldown-vite package' && e.target !== 'rolldown-vite package').map((edge, index) => ({
  id: `edge-${index}`,
  source: edge.source.toLowerCase().replace(/[^a-z0-9]/g, '-'),
  target: edge.target.toLowerCase().replace(/[^a-z0-9]/g, '-'),
  label: edge.label
}));

export const graphData: GraphData = {
  tools,
  edges,
  categories
};
