import type { Tool, Edge, ToolCategory, GraphData } from './types';

// Define categories with their levels and colors (Vercel-inspired palette)
export const categories: ToolCategory[] = [
  { id: 'metaframework', name: 'Meta Framework', level: 1, color: '#0070f3' },
  { id: 'framework', name: 'Framework', level: 2, color: '#00bcd4' },
  { id: 'library', name: 'Library', level: 3, color: '#f81ce5' },
  { id: 'bundler', name: 'Bundler', level: 4, color: '#ff6600' },
  { id: 'linter', name: 'Linter', level: 5, color: '#ffd93d' },
  { id: 'formatter', name: 'Formatter', level: 5, color: '#6bcf7f' },
  { id: 'minimizer', name: 'Minimizer', level: 5, color: '#ff4757' },
  { id: 'compiler', name: 'Compiler', level: 6, color: '#06ffa5' },
  { id: 'parser', name: 'Parser', level: 6, color: '#1fb6ff' },
  { id: 'runtime', name: 'Runtime', level: 7, color: '#4d4d4d' },
  { id: 'testing', name: 'Testing', level: 3, color: '#5f27cd' },
  { id: 'language-tool', name: 'Language Tool', level: 3, color: '#00d2d3' },
];

export const tools: Tool[] = [
  { name: 'TanStack Start', category: 'metaframework', logo: '/logos/tanstack-start.svg' },
  { name: 'SolidStart', category: 'metaframework', logo: '/logos/solidstart.svg' },
  { name: 'SvelteKit', category: 'metaframework', logo: '/logos/sveltekit.svg' },
  { name: 'Qwik City', category: 'metaframework', logo: '/logos/qwik-city.svg' },
  { name: 'Next.js', category: 'metaframework', logo: '/logos/nextjs.svg' },
  { name: 'Nuxt', category: 'metaframework', logo: '/logos/nuxt.svg' },
  { name: 'Remix', category: 'metaframework', logo: '/logos/remix.svg' },
  { name: 'Analog', category: 'metaframework', logo: '/logos/analog.svg' },
  { name: 'Astro / Starlight', category: 'framework', logo: '/logos/astro.svg' },
  { name: 'Mitosis', category: 'framework', logo: '/logos/mitosis.svg' },
  { name: 'Gatsby', category: 'framework', logo: '/logos/gatsby.svg' },
  { name: 'Docusaurus', category: 'framework', logo: '/logos/docusaurus.svg' },
  { name: 'Nitro', category: 'framework', logo: '/logos/nitro.svg' },
  { name: 'UnJS libs', category: 'framework', logo: '/logos/unjs.svg' },
  { name: 'Unplugin', category: 'framework', logo: '/logos/unplugin.svg' },
  { name: 'React Router', category: 'framework', logo: '/logos/react-router.svg' },
  { name: 'Preact', category: 'library', logo: '/logos/preact.svg' },
  { name: 'React', category: 'library', logo: '/logos/react.svg' },
  { name: 'Angular', category: 'library', logo: '/logos/angular.svg' },
  { name: 'Vue.js', category: 'library', logo: '/logos/vue.svg' },
  { name: 'Svelte', category: 'library', logo: '/logos/svelte.svg' },
  { name: 'Qwik', category: 'library', logo: '/logos/qwik.svg' },
  { name: 'Solid.js', category: 'library', logo: '/logos/solid.svg' },
  { name: 'LIT', category: 'library', logo: '/logos/lit.svg' },
  { name: 'Alpine', category: 'library', logo: '/logos/alpine.svg' },
  { name: 'Fresh', category: 'framework', logo: '/logos/fresh.svg' },
  { name: 'Volar.js', category: 'language-tool', logo: '/logos/volar.svg' },
  { name: 'Vitest', category: 'testing', logo: '/logos/vitest.svg' },
  { name: 'Vite', category: 'bundler', logo: '/logos/vite.svg' },
  { name: 'Parcel', category: 'bundler', logo: '/logos/parcel.svg' },
  { name: 'Turbopack', category: 'bundler', logo: '/logos/turbopack.svg' },
  { name: 'Webpack', category: 'bundler', logo: '/logos/webpack.svg' },
  { name: 'Rspack', category: 'bundler', logo: '/logos/rspack.svg' },
  { name: 'Farm', category: 'bundler', logo: '/logos/farm.svg' },
  { name: 'esbuild', category: 'bundler', logo: '/logos/esbuild.svg' },
  { name: 'Rollup', category: 'bundler', logo: '/logos/rollup.svg' },
  { name: 'Rolldown', category: 'bundler', logo: '/logos/rolldown.svg' },
  { name: 'Biome', category: 'linter', logo: '/logos/biome.svg' },
  { name: 'ESLint', category: 'linter', logo: '/logos/eslint.svg' },
  { name: 'Oxlint', category: 'linter', logo: '/logos/oxlint.svg' },
  { name: 'Prettier', category: 'formatter', logo: '/logos/prettier.svg' },
  { name: 'Terser', category: 'minimizer', logo: '/logos/terser.svg' },
  { name: 'SWC', category: 'compiler', logo: '/logos/swc.svg' },
  { name: 'Babel', category: 'compiler', logo: '/logos/babel.svg' },
  { name: 'tsc', category: 'compiler', logo: '/logos/tsc.svg' },
  { name: 'React Compiler', category: 'compiler', logo: '/logos/react-compiler.svg' },
  { name: 'ts-node', category: 'compiler', logo: '/logos/ts-node.svg' },
  { name: 'Acorn', category: 'parser', logo: '/logos/acorn.svg' },
  { name: 'OXC', category: 'compiler', logo: '/logos/oxc.svg' },
  { name: 'Deno', category: 'runtime', logo: '/logos/deno.svg' },
  { name: 'Bun', category: 'runtime', logo: '/logos/bun.svg' },
].map(tool => {
  const cat = categories.find(c => c.id === tool.category)!;
  return {
    ...tool,
    id: tool.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    category: cat,
    level: cat.level
  };
});

// Raw edge data from the user
const rawEdges = [
  { source: 'SolidStart', target: 'Solid.js', label: 'Based on' },
  { source: 'Analog', target: 'Angular', label: 'Based on' },
  { source: 'Nuxt', target: 'Vue.js', label: 'Based on' },
  { source: 'Remix', target: 'React Router', label: 'V2 Turned into' },
  { source: 'React Router', target: 'React', label: 'based on' },
  { source: 'Remix', target: 'React', label: 'until v3 based on' },
  { source: 'React', target: 'Preact', label: 'V3 started based on' },
  { source: 'Next.js', target: 'React', label: 'Based on' },
  { source: 'Docusaurus', target: 'React', label: 'Based on' },
  { source: 'Gatsby', target: 'React', label: 'Based on' },
  { source: 'Fresh', target: 'Preact', label: 'Based on' },
  { source: 'Mitosis', target: 'Solid.js', label: 'Compiles to' },
  { source: 'Mitosis', target: 'Qwik', label: 'Compiles to' },
  { source: 'Mitosis', target: 'Angular', label: 'Compiles to' },
  { source: 'Mitosis', target: 'Vue.js', label: 'Compiles to' },
  { source: 'Mitosis', target: 'Svelte', label: 'Compiles to' },
  { source: 'Mitosis', target: 'React', label: 'Compiles to' },
  { source: 'Volar.js', target: 'Vue.js', label: 'Language tools' },
  { source: 'Volar.js', target: 'Astro / Starlight', label: 'Language tools' },
  { source: 'Astro / Starlight', target: 'Solid.js', label: 'Astro supports components of' },
  { source: 'Astro / Starlight', target: 'Qwik', label: 'With @qwikdev/astro' },
  { source: 'Astro / Starlight', target: 'Angular', label: 'With @analogjs/astro-angular' },
  { source: 'Astro / Starlight', target: 'Vue.js', label: 'Astro supports components of' },
  { source: 'Astro / Starlight', target: 'Svelte', label: 'Astro supports components of' },
  { source: 'Astro / Starlight', target: 'Preact', label: 'Astro supports components of' },
  { source: 'Astro / Starlight', target: 'React', label: 'Astro supports components of' },
  { source: 'TanStack Start', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'SolidStart', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'LIT', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'Qwik City', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'Analog', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'Nuxt', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'SvelteKit', target: 'Vite', label: 'Bundling with Vite' },
  { source: 'Remix', target: 'Vite', label: 'Official bundling with' },
  { source: 'Remix', target: 'Webpack', label: 'Legacy bundling with' },
  { source: 'Next.js', target: 'Turbopack', label: 'dev from v13.1, build from v15.3 (experimental)' },
  { source: 'Vitest', target: 'Vite', label: 'build' },
  { source: 'Nuxt', target: 'Nitro', label: 'Use' },
  { source: 'Nitro', target: 'UnJS libs', label: 'Use' },
  { source: 'Vite', target: 'esbuild', label: 'Dev build' },
  { source: 'Vite', target: 'Rollup', label: 'Prod build' },
  { source: 'Vite', target: 'Rolldown', label: 'Build (experimental in v5)' },
  { source: 'Vite', target: 'rolldown-vite package', label: 'Use' },
  { source: 'rolldown-vite package', target: 'Rolldown', label: 'Dev & Prod Build' },
  { source: 'Webpack', target: 'Rspack', label: '1:1 replacement' },
  { source: 'Webpack', target: 'SWC', label: 'New loaders' },
  { source: 'Webpack', target: 'Terser', label: 'Common Minifier' },
  { source: 'esbuild', target: 'Rollup', label: 'successor' },
  { source: 'Rollup', target: 'Rolldown', label: 'successor' },
  { source: 'Rollup', target: 'Acorn', label: 'V3 and earlier parser' },
  { source: 'Rollup', target: 'OXC', label: 'V4 parser' },
  { source: 'Rollup', target: 'Terser', label: 'Common Minifier' },
  { source: 'Rolldown', target: 'OXC', label: 'Parser, Resolver, etc' },
  { source: 'Oxlint', target: 'OXC', label: 'Resolver' },
  { source: 'Oxlint', target: 'OXC', label: 'Experimental plugin' },
  { source: 'Biome', target: 'OXC', label: 'New JS/TS Plugin in v3.6' },
  { source: 'Biome', target: 'Prettier', label: 'Parser' },
  { source: 'Biome', target: 'ESLint', label: 'Parser' },
  { source: 'ESLint', target: 'Acorn', label: 'New parser (espree)' },
  { source: 'ESLint', target: 'Babel', label: 'Legacy parser (@babel/eslint-parser)' },
  { source: 'ESLint', target: 'tsc', label: 'TypeScript parser (@typescript-eslint/parser)' },
  { source: 'ESLint', target: 'SWC', label: 'Plugin (wip)' },
  { source: 'Prettier', target: 'Babel', label: 'Plugin' },
  { source: 'Prettier', target: 'Acorn', label: 'Parser' },
  { source: 'React Compiler', target: 'Babel', label: 'Plugin' },
  { source: 'React Compiler', target: 'SWC', label: 'Compiler' },
  { source: 'Unplugin', target: 'esbuild', label: 'Parse config files with' },
  { source: 'Unplugin', target: 'Acorn', label: 'Parse config files with' },
  { source: 'Terser', target: 'Acorn', label: 'parser (acorn/terser)' },
  { source: 'Vite', target: 'Unplugin', label: 'Use' },
  { source: 'Webpack', target: 'Unplugin', label: 'Use' },
  { source: 'Rollup', target: 'Unplugin', label: 'Use' },
  { source: 'esbuild', target: 'Unplugin', label: 'Use' },
  { source: 'Rspack', target: 'Unplugin', label: 'Use' },
  { source: 'Astro / Starlight', target: 'Acorn', label: 'Also used directly' },
  { source: 'SvelteKit', target: 'Acorn', label: 'Also used directly' },
  { source: 'Nuxt', target: 'Acorn', label: 'Also used directly' },
  { source: 'UnJS libs', target: 'Acorn', label: 'Also used directly' },
  { source: 'Fresh', target: 'Deno', label: 'Type checker' },
  { source: 'Deno', target: 'SWC', label: 'Type checker' },
  { source: 'ts-node', target: 'tsc', label: '' },
  { source: 'ts-node', target: 'SWC', label: '' },
  { source: 'ts-node', target: 'Bun', label: '' },
  { source: 'Turbopack', target: 'SWC', label: '' },
  { source: 'Rspack', target: 'SWC', label: '' },
  { source: 'Farm', target: 'SWC', label: '' },
  { source: 'Bun', target: 'SWC', label: '' },
  { source: 'esbuild', target: 'SWC', label: '' },
  { source: 'Parcel', target: 'SWC', label: '' },
  // SvelteKit uses Svelte
  { source: 'SvelteKit', target: 'Svelte', label: 'Uses' },
  // Qwik City uses Qwik
  { source: 'Qwik City', target: 'Qwik', label: 'Uses' },
];

// Transform raw data to typed structures
export const edges: Edge[] = rawEdges.filter(e => e.source !== 'rolldown-vite package' && e.target !== 'rolldown-vite package').map((edge, index) => ({
  id: `edge-${index}`,
  source: edge.source.toLowerCase().replace(/[^a-z0-9]/g, '-'),
  target: edge.target.toLowerCase().replace(/[^a-z0-9]/g, '-'),
  label: edge.label
}));

export const graphData: GraphData = {
  tools,
  edges,
  categories
};
